title: digital.gov
email: DigitalGov@gsa.gov

twitter_username: digitalgov
# github_username:  18F

gems:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag

whitelist:
  - jekyll-redirect-from

styles:
  # - /assets/uswds/css/uswds.min.css
  - /assets/main.css

# Exlude files from being present in the build site
exclude:
  - ".gitignore"
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - package.json
  - gulpfile.js
  - node_modules
  - README.md
  # - content/about/
  # - content/services/
  - content/communities/_x/
  # - content/resources/
  - content/resources/1/
  - content/resources/2/
  - content/resources/3/
  - content/pages/1/
  - content/pages/2/
  - content/pages/3/
  - content/pages/_x/
  - content/un-sorted/
  - content/pages/_x/
