title                   : "Digital.gov"
baseURL                 : "/"
languageCode            : "en-us"
theme                   : "digital.gov"
themesDir               : "./themes"

MetaDataFormat          : "yaml"
DefaultContentLanguage  : "en"
SectionPagesMenu        : "main"
Paginate                : 15
googleAnalytics         : ""
enableRobotsTXT         : true
enableEmoji             : true
enableGitInfo           : true
buildFuture             : true


ignoreFiles:
  - "^_template"
  - "content/_tmp/*"
  - "content/images/*"
  - "content/_archived/*"
# uncomment the following for a dev mode that excludes posts before 2017
  - "content/posts/201[0-6]"

sitemap:
  changefreq            : "monthly"
  priority              : 0.5
  filename              : "sitemap.xml"

outputFormats:
  SiteImages:
    mediaType: "application/json"
    baseName: "siteimages"
    isPlainText: true
    notAlternative: true
  RSS:
    mediatype: "application/rss"
    baseName: "feed"

rssLimit: 20

outputs:
  home: ["HTML","RSS", "SiteImages", "JSON"]
  section: ["HTML","RSS", "JSON"]
  page: ["HTML","RSS", "JSON"]
  taxonomy: ["HTML","RSS", "JSON"]
  taxonomyTerm: ["HTML","RSS", "JSON"]

blackfriday:
  fractions: false

params:
  description: "Weâ€™re building a modern government, together."
  cdnurl: "https://s3.amazonaws.com/digitalgov"
  git_org: "GSA"
  git_repo: "digitalgov.gov"
  devmode: true

permalinks:
  posts                 : ":year/:month/:day/:slug/"
  events                : "event/:year/:month/:day/:slug/"

preserveTaxonomyNames   : true
taxonomies:
  tag                   : "tag"
  category              : "categories"
  author                : "authors"

pluralizelisttitles     : false

menu:
  primary:
    - Name            : "News"
      Identifier      : "news"
      URL             : "/news/"
      Weight          : 1
    - Name            : "Events"
      Identifier      : "events"
      URL             : "/events/"
      Weight          : 2
    - Name            : "Resources"
      Identifier      : "resources"
      URL             : "/resources/"
      Weight          : 3
    - Name            : "Communities"
      Identifier      : "communities"
      URL             : "/communities/"
      Weight          : 4
    - Name            : "Services"
      Identifier      : "services"
      URL             : "/services/"
      Weight          : 5
    - Name            : "Subscribe"
      Identifier      : "subscribe"
      URL             : "/subscribe/"
      Weight          : 6

  secondary:
    - Name            : "Challenges"
      Identifier      : "challenges"
      URL             : "/categories/challenges/"
      Weight          : 1
    - Name            : "Crowdsourcing & Citizen Science"
      Parent          : "challenges"
      Identifier      : "crowdsourcing-and-citizen-science"
      URL             : "/categories/crowdsourcing-and-citizen-science/"
      Weight          : 11

    - Name            : "Code"
      Identifier      : "code"
      URL             : "/categories/code/"
      Weight          : 2
    - Name            : "API"
      Parent          : "code"
      Identifier      : "api"
      URL             : "/categories/api/"
      Weight          : 20
    - Name            : "Data"
      Parent          : "code"
      Identifier      : "data"
      URL             : "/categories/data/"
      Weight          : 21

    - Name            : "Content"
      Identifier      : "content"
      URL             : "/categories/content/"
      Weight          : 3
    - Name            : "Video"
      Parent          : "content"
      Identifier      : "video"
      URL             : "/categories/video/"
      Weight          : 20
    - Name            : "Writing"
      Parent          : "content"
      Identifier      : "writing"
      URL             : "/categories/writing/"
      Weight          : 21

    - Name            : "Managing Digital"
      Identifier      : "managing-digital"
      URL             : "/categories/managing-digital/"
      Weight          : 4
    - Name            : "Governance"
      Parent          : "managing-digital"
      Identifier      : "governance"
      URL             : "/categories/governance/"
      Weight          : 41
    - Name            : "Strategy & Policy"
      Parent          : "managing-digital"
      Identifier      : "governance"
      URL             : "/categories/strategy-and-policy/"
      Weight          : 42

    - Name            : "Metrics"
      Identifier      : "resources"
      URL             : "/categories/metrics/"
      Weight          : 5

    - Name            : "Mobile"
      Identifier      : "mobile"
      URL             : "/categories/mobile/"
      Weight          : 6

    - Name            : "Social media"
      Identifier      : "social-media"
      URL             : "/categories/social-media/"
      Weight          : 7

    - Name            : "UX"
      Identifier      : "ux"
      URL             : "/categories/ux/"
      Weight          : 7
    - Name            : "Accessibility"
      Parent          : "ux"
      Identifier      : "accessibility"
      URL             : "/categories/accessibility/"
      Weight          : 71
    - Name            : "Design"
      Parent          : "ux"
      Identifier      : "design"
      URL             : "/categories/design/"
      Weight          : 71
    - Name            : "User Testing & Research"
      Parent          : "ux"
      Identifier      : "user-testing-and-research"
      URL             : "/categories/user-testing-and-research/"
      Weight          : 71

  contribute:
    - Name            : "Write for us"
      Identifier      : "contribute"
      URL             : "/contribute/"
      Weight          : 1
    - Name            : "Host and event"
      Identifier      : "digitalgov-university"
      URL             : "/digitalgov-university/"
      Weight          : 2
    - Name            : "Edit on GitHub"
      Identifier      : "edit"
      URL             : "https://github.com/GSA/digitalgov.gov/"
      Weight          : 3

  about:
    - Name            : "About Us"
      Identifier      : "about"
      URL             : "/about/"
      Weight          : 1
    - Name            : "Site Policies"
      Identifier      : "policies"
      URL             : "/policies/"
      Weight          : 2
