title                   : "Digital.gov"
baseURL                 : "/"
languageCode            : "en-us"
theme                   : "digital.gov"
themesDir               : "./themes"

MetaDataFormat          : "yaml"
DefaultContentLanguage  : "en"
SectionPagesMenu        : "main"
Paginate                : 20
googleAnalytics         : ""
enableRobotsTXT         : true
enableEmoji             : true
enableGitInfo           : true
buildFuture             : true

ignoreFiles:
  - "^_template"
  - "content/_tmp/*"
  - "content/images/*"
  - "content/_archived/*"

sitemap:
  changefreq            : "daily"
  priority              : 1
  filename              : "sitemap.xml"

outputFormats:
  SiteImages:
    mediaType: "application/json"
    baseName: "siteimages"
    isPlainText: true
    notAlternative: true
  RSS:
    mediatype: "application/rss"
  JSON:
    mediatype: "application/json"

preserveTaxonomyNames   : true

taxonomies:
  topic                 : "topics"
  author                : "authors"

outputs:
  home: ["HTML","RSS", "SiteImages", "JSON"]
  section: ["HTML","RSS", "JSON"]
  page: ["HTML","RSS", "JSON"]
  taxonomy: ["HTML","RSS", "json"]

# Goldmark is from Hugo 0.60 the default library used for Markdown.
# https://gohugo.io/getting-started/configuration-markup/#goldmark
markup:
  defaultMarkdownHandler: blackfriday



params:
  description: "Guidance on building better digital services in government"
  agency_refer: "U.S. General Services Administration"
  cdnurl                : "https://s3.amazonaws.com/digitalgov"
  git_org               : "GSA"
  git_repo              : "digitalgov.gov"
  url_shortener_login: jeremyz
  url_shortener_api: d0ac464a2dfad044147e9537fd51503b
  devmode               : false

  # Homepage settings
  dg_tagline: "Build better digital services"

  # number of news items to include on the homepage
  stream_count: 10

  # number of events to include on the homepage
  events_count: 3

  #base SEO keywords
  keywords:
    - digital
    - government
    - technology
    - civic-tech


refLinksNotFoundURL: https://digital.gov/resources/

permalinks:
  posts                 : ":year/:month/:day/:slug/"
  events                : "event/:year/:month/:day/:slug/"

# Related Posts Config
# See: https://gohugo.io/content-management/related/#default-configuration
related:
  threshold: 100
  includeNewer: true
  toLower: false
  indices:
  - name: topics
    weight: 100

pluralizelisttitles     : false

menu:
  primary:
    - Name            : "News"
      Identifier      : "news"
      URL             : "/news/"
      Weight          : 1
    - Name            : "Events"
      Identifier      : "events"
      URL             : "/events/"
      Weight          : 2
    - Name            : "Resources"
      Identifier      : "resources"
      URL             : "/resources/"
      Weight          : 3
    - Name            : "Communities"
      Identifier      : "communities"
      URL             : "/communities/"
      Weight          : 4
    - Name            : "Services"
      Identifier      : "services"
      URL             : "/services/"
      Weight          : 5

  contribute:
    - Name            : "Write for us"
      Identifier      : "contribute"
      URL             : "/contribute/"
      Weight          : 1
    - Name            : "Host an event"
      Identifier      : "digitalgov-university"
      URL             : "/digitalgov-university/"
      Weight          : 2
    - Name            : "Edit on GitHub"
      Identifier      : "edit"
      URL             : "https://github.com/GSA/digitalgov.gov/"
      Weight          : 3

  about:
    - Name            : "About Us"
      Identifier      : "about"
      URL             : "/about/"
      Weight          : 1
    - Name            : "Site Policies"
      Identifier      : "policies"
      URL             : "/policies/"
      Weight          : 2
