name: "Mark stale issues and pull requests"

# Run at 07:00 on every Monday
on:
  schedule:
  - cron: "0 7 * * mon"

jobs:
  stale:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'Hello! ðŸ‘‹ It looks like this issue is stale because it has been open 60 days with no activity. This is usually because the request was already solved or it is no longer applicable. If this issue should remain open, remove the stale label or add a comment. Otherwise, this will be closed in 7 days.'
        stale-pr-message: 'Hello! ðŸ‘‹ It looks like this pull request is stale because it has been open 60 days with no activity. This is usually because the request was already solved or it is no longer applicable. If this pull request should remain open, remove the stale label or add a comment. Otherwise, this will be closed in 7 days.'
        days-before-stale: 120
        days-before-close: 14
        stale-issue-label: '[status] stale'
        stale-pr-label: '[status] stale'
        exempt-issue-label: '---- HOLD ----, Bug: broken links, Bug: Content Cleanup'
        exempt-pr-label: '---- HOLD ----'
